### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by halkeye** [halkeye/gatsby-theme-nodeschool#10]
as per https://github.com/nodeschool/vancouver/pull/110#issuecomment-547908368

> Awesome. I need to learn more about those gatsby themes.
> Is it possible to customize other contents? Like, a lot of other chapters are not in English.

**Comment by halkeye** [comment]
@victorperin more todo items! i'll take a look into this i think once i finish cleaning up things a bit more, maybe ask on the gatsby help threads

**Comment by halkeye** [comment]
Oooh https://www.gatsbyjs.org/packages/gatsby-theme-localization/

**Comment by pethersonmoreno** [comment]
Hi @halkeye , I'm helping @victorperin in Nodeschool Campinas.

I've already started i18n support:

- branch I'm working: https://github.com/pethersonmoreno/nodeschool-campinas-gatsby/tree/feat/translate-to-pt-br

I need help to do it in the right way.

Until sunday I will send a Pullrquest here.

**Comment by pethersonmoreno** [comment]
This Pullrequest can solve this issue:

- https://github.com/halkeye/gatsby-theme-nodeschool/pull/12

With a few changes I think it can be changed to use gatsby-theme-localization:

- https://www.gatsbyjs.org/packages/gatsby-theme-localization/

**Comment by pethersonmoreno** [comment]
These changes are used in:

- https://github.com/nodeschool/campinas/tree/feat/changes-to-campinas

And can see it published at https://pethersonmoreno.github.io/nodeschool-campinas/

This Pullrequest also uses changes in the gatsby-source-meetup package:

- https://github.com/phacks/gatsby-source-meetup/pull/9

**Comment by pethersonmoreno** [comment]
Applied changes to use gatsby-theme-localization.

**Comment by halkeye** [comment]
This is closed by #12
